export const salatTime: I18nSalah[] = [
  "Fajr",
  "Zuhr",
  "Asr",
  "Maghrib",
  "Isha",
  "Others",
];

const fajr: ISalat[] = [
  {
    name: "Tahajjud",
    time: "Fajr",
    priority: "Nafal",
    rakats: 8,
    complete: false,
    concentration: 0,
    before: true,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Fajr",
    time: "Fajr",
    priority: "Farz",
    rakats: 2,
    complete: false,
    jamat: false,
    firstTakbeer: false,
    concentration: 0,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Fajr",
    time: "Fajr",
    priority: "Sunnah",
    rakats: 2,
    complete: false,
    concentration: 0,
    before: true,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Ishraq",
    time: "Fajr",
    priority: "Nafal",
    rakats: 4,
    complete: false,
    concentration: 0,
    before: true,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Chasht",
    time: "Fajr",
    priority: "Nafal",
    rakats: 4,
    complete: false,
    concentration: 0,
    before: true,
    id: "",
    userId: "",
    date: new Date(),
  },
];

const zuhr: ISalat[] = [
  {
    name: "Zuhr",
    time: "Zuhr",
    priority: "Sunnah",
    rakats: 4,
    complete: false,
    concentration: 0,
    before: true,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Zuhr",
    time: "Zuhr",
    priority: "Farz",
    rakats: 4,
    complete: false,
    jamat: false,
    firstTakbeer: false,
    concentration: 0,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Zuhr",
    time: "Zuhr",
    priority: "Sunnah",
    rakats: 2,
    complete: false,
    concentration: 0,
    after: true,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Jumuah",
    time: "Zuhr",
    priority: "Sunnah",
    rakats: 4,
    complete: false,
    concentration: 0,
    before: true,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Jumuah",
    time: "Zuhr",
    priority: "Farz",
    rakats: 2,
    complete: false,
    concentration: 0,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Jumuah",
    time: "Zuhr",
    priority: "Sunnah",
    rakats: 4,
    complete: false,
    concentration: 0,
    after: true,
    id: "",
    userId: "",
    date: new Date(),
  },
];

const asr: ISalat[] = [
  {
    name: "Asr",
    time: "Asr",
    priority: "Sunnah",
    rakats: 4,
    complete: false,
    concentration: 0,
    before: true,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Asr",
    time: "Asr",
    priority: "Farz",
    rakats: 4,
    complete: false,
    concentration: 0,
    jamat: false,
    firstTakbeer: false,
    id: "",
    userId: "",
    date: new Date(),
  },
];

const maghrib: ISalat[] = [
  {
    name: "Maghrib",
    time: "Maghrib",
    priority: "Farz",
    rakats: 3,
    complete: false,
    concentration: 0,
    jamat: false,
    firstTakbeer: false,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Maghrib",
    time: "Maghrib",
    priority: "Sunnah",
    rakats: 2,
    complete: false,
    concentration: 0,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Awabeen",
    time: "Maghrib",
    priority: "Nafal",
    rakats: 6,
    complete: false,
    concentration: 0,
    id: "",
    userId: "",
    date: new Date(),
  },
];

const isha: ISalat[] = [
  {
    name: "Isha",
    time: "Isha",
    priority: "Farz",
    rakats: 4,
    complete: false,
    concentration: 0,
    jamat: false,
    firstTakbeer: false,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Isha",
    time: "Isha",
    priority: "Sunnah",
    rakats: 2,
    complete: false,
    concentration: 0,
    after: true,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Taraweeh",
    time: "Isha",
    priority: "Sunnah",
    rakats: 20,
    complete: false,
    concentration: 0,
    after: true,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Witr",
    time: "Isha",
    priority: "Wajib",
    rakats: 3,
    complete: false,
    concentration: 0,
    id: "",
    userId: "",
    date: new Date(),
  },
];

const others: ISalat[] = [
  {
    name: "Janazah",
    time: "Others",
    priority: "Janazah",
    rakats: 0,
    complete: false,
    jamat: false,
    firstTakbeer: false,
    concentration: 0,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Tasbeeh",
    time: "Others",
    priority: "Nafal",
    rakats: 4,
    complete: false,
    concentration: 0,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Tawbah",
    time: "Others",
    priority: "Nafal",
    rakats: 2,
    complete: false,
    concentration: 0,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Kusuf",
    time: "Others",
    priority: "Nafal",
    rakats: 2,
    complete: false,
    concentration: 0,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Khusuf",
    time: "Others",
    priority: "Nafal",
    rakats: 2,
    complete: false,
    concentration: 0,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Istika",
    time: "Others",
    priority: "Nafal",
    rakats: 2,
    complete: false,
    concentration: 0,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Istikhara",
    time: "Others",
    priority: "Nafal",
    rakats: 2,
    complete: false,
    concentration: 0,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Istikhara",
    time: "Others",
    priority: "Nafal",
    rakats: 2,
    complete: false,
    concentration: 0,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Hajat",
    time: "Others",
    priority: "Nafal",
    rakats: 2,
    complete: false,
    concentration: 0,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Tahiyatul_Azu",
    time: "Others",
    priority: "Nafal",
    rakats: 2,
    complete: false,
    concentration: 0,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Dukhulul_Masjid",
    time: "Others",
    priority: "Nafal",
    rakats: 2,
    complete: false,
    concentration: 0,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Shukr",
    time: "Others",
    priority: "Nafal",
    rakats: 2,
    complete: false,
    concentration: 0,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Shukr",
    time: "Others",
    priority: "Nafal",
    rakats: 2,
    complete: false,
    concentration: 0,
    id: "",
    userId: "",
    date: new Date(),
  },
];

export const allSalat: ISalat[] = [
  ...fajr,
  ...zuhr,
  ...asr,
  ...maghrib,
  ...asr,
  ...isha,
  ...others,
];
