export const salatTime: I18nSalah[] = [
  "Fajr",
  "Zuhr",
  "Asr",
  "Maghrib",
  "Isha",
  "Others",
];

export const allSalat: ISalat[] = [
  {
    name: "Fajr",
    time: "Fajr",
    priority: "Farz",
    rakats: 2,
    complete: false,
    jamat: false,
    firstTakbeer: false,
    concentration: 0,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Fajr",
    time: "Fajr",
    priority: "Sunnah",
    rakats: 2,
    complete: false,
    concentration: 0,
    before: true,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Zuhr",
    time: "Zuhr",
    priority: "Sunnah",
    rakats: 4,
    complete: false,
    concentration: 0,
    before: true,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Zuhr",
    time: "Zuhr",
    priority: "Farz",
    rakats: 4,
    complete: false,
    jamat: false,
    firstTakbeer: false,
    concentration: 0,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Zuhr",
    time: "Zuhr",
    priority: "Sunnah",
    rakats: 2,
    complete: false,
    concentration: 0,
    after: true,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Jumuah",
    time: "Zuhr",
    priority: "Sunnah",
    rakats: 4,
    complete: false,
    concentration: 0,
    before: true,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Jumuah",
    time: "Zuhr",
    priority: "Farz",
    rakats: 2,
    complete: false,
    concentration: 0,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Jumuah",
    time: "Zuhr",
    priority: "Sunnah",
    rakats: 4,
    complete: false,
    concentration: 0,
    after: true,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Asr",
    time: "Asr",
    priority: "Sunnah",
    rakats: 4,
    complete: false,
    concentration: 0,
    before: true,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Asr",
    time: "Asr",
    priority: "Farz",
    rakats: 4,
    complete: false,
    concentration: 0,
    jamat: false,
    firstTakbeer: false,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Maghrib",
    time: "Maghrib",
    priority: "Farz",
    rakats: 3,
    complete: false,
    concentration: 0,
    jamat: false,
    firstTakbeer: false,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Maghrib",
    time: "Maghrib",
    priority: "Sunnah",
    rakats: 2,
    complete: false,
    concentration: 0,
    jamat: false,
    firstTakbeer: false,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Isha",
    time: "Isha",
    priority: "Farz",
    rakats: 4,
    complete: false,
    concentration: 0,
    jamat: false,
    firstTakbeer: false,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Isha",
    time: "Isha",
    priority: "Sunnah",
    rakats: 2,
    complete: false,
    concentration: 0,
    after: true,
    id: "",
    userId: "",
    date: new Date(),
  },
  {
    name: "Witr",
    time: "Isha",
    priority: "Wajib",
    rakats: 3,
    complete: false,
    concentration: 0,
    id: "",
    userId: "",
    date: new Date(),
  },
];
