import { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Proactive Muslim",
  description: "Generated by Sunnah-IT",
};

// Since we have a `not-found.tsx` page on the root, a layout file
// is required, even if it's just passing children through.
const RootLayout = ({ children }: Readonly<IChildren>) => {
  return children;
};

export default RootLayout;
