import { ReduxProviders } from "@/Redux/provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { FC, PropsWithChildren } from "react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<Readonly<PropsWithChildren>> = ({ children }) => (
  <html lang="en">
    <body className={inter.className}>
      <ReduxProviders>{children}</ReduxProviders>
    </body>
  </html>
);

export default RootLayout;
